routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();
//Program
Route::get('master','HomeController@master')->middleware('auth');

Route::post('login-home','HomeController@login');

Route::get('logout',function(){
    Auth::logout();
    return redirect('login');
});

Route::resource('sdm','SdmController')->middleware('auth');
Route::resource('master-unit','UnitController')->middleware('auth');
Route::resource('master-user','UserController')->middleware('auth');
Route::get('sdm-detail/{iduser}','UserController@sdm_detail')->middleware('auth');
Route::post('sdm-detail-simpan/{iduser}','UserController@sdm_detail_simpan')->middleware('auth');
Route::resource('master-jenis','JenisBencanaController')->middleware('auth');
Route::resource('master-kebutuhan','JenisKebutuhanController')->middleware('auth');

Route::resource('data-laporan','InstrumenLaporangKejadianController')->middleware('auth');
Route::post('data-laporan-verifikasi/{id}','InstrumenLaporangKejadianController@data_laporan_verifikasi')->middleware('auth');
Route::post('data-laporan-tidak-lengkap/{id}','InstrumenLaporangKejadianController@data_laporan_tidak_lengkap')->middleware('auth');
Route::post('data-laporan-upload-nodin/{id}','InstrumenLaporangKejadianController@data_laporan_upload_nodin')->middleware('auth');
Route::post('data-laporan-upload-sk/{id}','InstrumenLaporangKejadianController@data_laporan_upload_sk')->middleware('auth');
Route::post('data-laporan-disposisi/{id}','InstrumenLaporangKejadianController@data_laporan_disposisi')->middleware('auth');
Route::get('cetak-laporan/{id}','InstrumenLaporangKejadianController@cetak_laporan')->middleware('auth');

Route::resource('data-bantuan-jaminan','InstrumenJHPKBSController')->middleware('auth');
Route::post('data-bantuan-jaminan-verifikasi/{id}','InstrumenJHPKBSController@data_laporan_verifikasi')->middleware('auth');
Route::post('data-bantuan-jaminan-tidak-lengkap/{id}','InstrumenJHPKBSController@data_laporan_tidak_lengkap')->middleware('auth');
Route::post('data-bantuan-jaminan-upload-nodin/{id}','InstrumenJHPKBSController@data_laporan_upload_nodin')->middleware('auth');
Route::post('data-bantuan-jaminan-upload-sk/{id}','InstrumenJHPKBSController@data_laporan_upload_sk')->middleware('auth');
Route::post('data-bantuan-jaminan-disposisi/{id}','InstrumenJHPKBSController@data_laporan_disposisi')->middleware('auth');
Route::get('cetak-laporan-bj/{id}','InstrumenJHPKBSController@cetak_laporan')->middleware('auth');

Route::resource('data-bantuan-santuan','InstrumenAssesmentController')->middleware('auth');
Route::post('data-bantuan-santuan-verifikasi/{id}','InstrumenAssesmentController@data_laporan_verifikasi')->middleware('auth');
Route::post('data-bantuan-santuan-tidak-lengkap/{id}','InstrumenAssesmentController@data_laporan_tidak_lengkap')->middleware('auth');
Route::post('data-bantuan-santuan-upload-nodin/{id}','InstrumenAssesmentController@data_laporan_upload_nodin')->middleware('auth');
Route::post('data-bantuan-santuan-upload-sk/{id}','InstrumenAssesmentController@data_laporan_upload_sk')->middleware('auth');
Route::post('data-bantuan-santuan-disposisi/{id}','InstrumenAssesmentController@data_laporan_disposisi')->middleware('auth');
Route::get('cetak-laporan-bs/{id}','InstrumenAssesmentController@cetak_laporan')->middleware('auth');

Route::resource('data-bantuan-bahan-bangunan','InstrumenAssesmentPemulianController')->middleware('auth');
Route::post('data-bantuan-bahan-bangunan-verifikasi/{id}','InstrumenAssesmentPemulianController@data_laporan_verifikasi')->middleware('auth');
Route::post('data-bantuan-bahan-bangunan-tidak-lengkap/{id}','InstrumenAssesmentPemulianController@data_laporan_tidak_lengkap')->middleware('auth');
Route::post('data-bantuan-bahan-bangunan-upload-nodin/{id}','InstrumenAssesmentPemulianController@data_laporan_upload_nodin')->middleware('auth');
Route::post('data-bantuan-bahan-bangunan-upload-sk/{id}','InstrumenAssesmentPemulianController@data_laporan_upload_sk')->middleware('auth');
Route::post('data-bantuan-bahan-bangunan-disposisi/{id}','InstrumenAssesmentPemulianController@data_laporan_disposisi')->middleware('auth');
Route::get('cetak-laporan-bb/{id}','InstrumenAssesmentPemulianController@cetak_laporan')->middleware('auth');

Route::get('unduh-file/{dir}/{file}','HomeController@unduh');
Route::get('pilih-kab/{idprov}','HomeController@pilih_kab');

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
});
Route::get('json_user/{user}/{pass}','JsonController@json_user');
Route::get('json_provinsi','JsonController@json_provinsi');
Route::get('json_kabupaten/{idprov}','JsonController@json_kabupaten');
Route::get('json_kebutuhan','JsonController@json_kebutuhan');
Route::get('json_laporan/{iduser}','JsonController@getlaporan');
Route::get('json_notifikasi/{iduser}','JsonController@json_notifikasi');
 
Route::get('update-koordinat','HomeController@update_koordinat');
Route::get('lihat-dokumen/{dir}/{file}','HomeController@lihat_dokumen');

Route::get('kirim-notif','HomeController@kirim_notif');

resources/views/pages/master/jenis-kebutuhan.blade.php
@extends('layouts.master')
@section('title')
    <title>Data Jenis Kebutuhan - iPSKBS</title>
@endsection

@section('head-section')
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Home</span> - Dashboard</h4>
        </div>
        <div class="heading-elements">
            <div class="heading-btn-group">
                <a href="#" class="btn btn-link btn-float text-size-small has-text"><i class="icon-bars-alt text-primary"></i><span>Statistics</span></a>
                <a href="#" class="btn btn-link btn-float text-size-small has-text"><i class="icon-calculator text-primary"></i> <span>Invoices</span></a>
                <a href="#" class="btn btn-link btn-float text-size-small has-text"><i class="icon-calendar5 text-primary"></i> <span>Schedule</span></a>
            </div>
        </div>
    </div>
@endsection
@section('breadcumb')
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="icon-home2 position-left"></i> Home</a></li>
            <li><a href="{{url('master')}}">Master</a></li>
            <li class="active">Jenis Kebutuhan</li>
        </ul>
        <ul class="breadcrumb-elements">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-gear position-left"></i>
                    Settings
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="{{url('logout')}}"><i class="icon-switch"></i> Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
@endsection

@section('konten')

<div class="row">
    
    @if (Session::has('errors'))
		<div class="col-md-12">
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				<strong>Oops, terjadi kesalahan. </strong>
				<ul style="font-size:12px;margin-top:5px;">
					@if ($errors->has('jenis'))
						<li> &nbsp; - {{ $errors->first('jenis') }}</li>
					@endif
					@if ($errors->has('flag'))
						<li> &nbsp; - {{ $errors->first('flag') }}</li>
					@endif
					
				</ul>
			</div>
		</div>
    @endif
    <div class="col-md-12">
        <a href="" class="btn btn-xs btn-success pull-right" data-toggle="modal" data-target="#modaltambah">+ Tambah Data</a>
    </div>
	<div class="col-lg-12">
		<!-- Traffic sources -->
		<div class="panel panel-flat" style="min-height:350px !important;">
			<div class="panel-heading">
                <h3 class="panel-title">Daftar Unit</h3>   
                
            </div>
            <div class="container-fluid">
                <table class="table table-basic table-striped" id="table">
                    <thead>
                        <tr>
                            <th class="text-left">No</th>
                            <th class="text-left">Jenis</th>
                            <th>Keterangan</th>
                            <th>Status</th>
                            <th class="text-center">#</th>
                        </tr>
                    </thead>
                @php
                    $no=1;
                @endphp
                <tbody>
                
                    @foreach ($jenis as $im)

                        <tr>
                                <td class="text-left"><b>{{$no}}</b></td>
                                <td class="">{{$im->jenis}}</td>
                                <td class="text-left">{{$im->keterangan}}</td>
                                <td>
                                    @if ($im->flag==1)
                                        <span class="label label-primary">Aktif</span>
                                    @else
                                        <span class="label label-danger">Tidak Aktif</span>    
                                    @endif
                                </td>
                                <td class="text-center">
                                    <div style="width:100px" class="text-center">
                                        <a class="btn btn-xs btn-info btn-edit" data-toggle="modal" data-target="#modalubah" data-value="{{ $im->id }}">
                                                    <i class="icon-pencil"></i>
                                                </a>
                                        <a href="#" class="btn btn-xs btn-danger btn-delete" data-toggle="modal" data-target="#modalhapus" data-value="{{ $im->id }}">
                                        <i class="icon-trash"></i>
                                    </a>  
                                </div> 
                                </td>
                            </tr>
                           
                        
                        @php
                            $no++;
                        @endphp
                    @endforeach

                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('modal')
	<div class="modal fade" id="modaltambah" tabindex="-1" role="dialog">
		<div class="modal-dialog ">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Tambah Data Jenis Kebutuhan</h4>
				</div>
				<div class="modal-body">
					<form action="{{ route('master-kebutuhan.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                 <div class="form-group">	
                                    <label>Jenis</label>
                                    <input type="text" name="jenis" class="form-control" placeholder="Jenis">  
                                </div>  
                                <div class="form-group">	
                                    <label>Keterangan</label>
                                    <input type="text" name="keterangan"  class="form-control" placeholder="Keterangan">  
                                </div>  
                                <div class="form-group">	
                                    <label>Status</label>
                                    <select name="flag"  palceholder="Status" class="selectbox" style="">
                                        <option>- Pilih -</option>
                                        <option value="0">Tidak Aktif</option>
                                        <option value="1">Aktif</option>
                                        
                                    </select>
                                </div> 
                            </div>
                           
                        </div>
						
						
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalubah" tabindex="-1" role="dialog">
		<div class="modal-dialog ">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Ubah Data SDM</h4>
				</div>
				<div class="modal-body">
					<form id="form-update" method="POST" enctype="multipart/form-data">
						@csrf
						@method('PUT')
						<div class="row">
                            <div class="col-md-12">
                               
                                <div class="form-group">	
                                    <label>Jenis</label>
                                    <input type="text" name="jenis" id="jenis" class="form-control" placeholder="Jenis">  
                                </div>  
                                <div class="form-group">	
                                    <label>Keterangan</label>
                                    <input type="text" name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan">  
                                </div>  
                                <div class="form-group">	
                                    <label>Status</label>
                                    <select name="flag" id="flag" palceholder="Status" class="selectbox" style="">
                                        <option>- Pilih -</option>
                                        <option value="0">Tidak Aktif</option>
                                        <option value="1">Aktif</option>
                                        
                                    </select>
                                </div>  
                                
                            </div>
                        </div>  
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan Perubahan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalhapus" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Konfirmasi Hapus Data Jenis</h4>
				</div>
				<div class="modal-body">
					<h5>Apakah anda yakin akan menghapus data ini?</h5>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit();" style="cursor:pointer;">Ya, Saya Yakin</a>
					<form id="form-delete" method="POST" style="display: none;">
						@csrf
						@method('DELETE')
					</form>
				</div>
			</div>
		</div>
	</div>
@endsection
@section('footscript')
    <script type="text/javascript" src="{{asset('assets/js/plugins/forms/selects/bootstrap_select.min.js')}}"></script>
    <script>
    $(document).ready(function(){
        $('#table').DataTable();
        $(".selectbox").selectpicker({
            
        });
    	// binding data to modal edit
        $('#table').on('click', '.btn-edit', function(){
            var id = $(this).data('value')
			var flag = $("select#flag").selectpicker();
			
            $.ajax({
                url: "{{ url('master-kebutuhan') }}/"+id+"/edit",
                success: function(res) {
					$('#form-update').attr('action', "{{ url('master-kebutuhan') }}/"+id)
					$('#jenis').val(res.jenis);
                    $('#keterangan').val(res.keterangan);
                    flag.selectpicker('val', res.flag);
                   
                }
            })
        })

		// delete action
        $('#table').on('click', '.btn-delete', function(){
            var id = $(this).data('value')
			$('#form-delete').attr('action', "{{ url('master-kebutuhan') }}/"+id)			
        })
        
    });
    
    </script>
<style>
.selectbox {
    width: 100% !important;
}

</style>
@endsection

resources/views/pages/master/jenis.blade.php
@extends('layouts.master')
@section('title')
    <title>Data Jenis Bencana - iPSKBS</title>
@endsection

@section('head-section')
    <div class="page-header-content">
        <div class="page-title">
            <h4><i class="icon-arrow-left52 position-left"></i> <span class="text-semibold">Home</span> - Dashboard</h4>
        </div>
        <div class="heading-elements">
            <div class="heading-btn-group">
                <a href="#" class="btn btn-link btn-float text-size-small has-text"><i class="icon-bars-alt text-primary"></i><span>Statistics</span></a>
                <a href="#" class="btn btn-link btn-float text-size-small has-text"><i class="icon-calculator text-primary"></i> <span>Invoices</span></a>
                <a href="#" class="btn btn-link btn-float text-size-small has-text"><i class="icon-calendar5 text-primary"></i> <span>Schedule</span></a>
            </div>
        </div>
    </div>
@endsection
@section('breadcumb')
    <div class="breadcrumb-line">
        <ul class="breadcrumb">
            <li><a href="{{url('/')}}"><i class="icon-home2 position-left"></i> Home</a></li>
            <li><a href="{{url('master')}}">Master</a></li>
            <li class="active">Jenis Bencana</li>
        </ul>
        <ul class="breadcrumb-elements">
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-gear position-left"></i>
                    Settings
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="{{url('logout')}}"><i class="icon-switch"></i> Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
@endsection

@section('konten')

<div class="row">
    
    @if (Session::has('errors'))
		<div class="col-md-12">
			<div class="alert alert-danger alert-dismissible" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
				<strong>Oops, terjadi kesalahan. </strong>
				<ul style="font-size:12px;margin-top:5px;">
					@if ($errors->has('jenis'))
						<li> &nbsp; - {{ $errors->first('jenis') }}</li>
					@endif
					@if ($errors->has('flag'))
						<li> &nbsp; - {{ $errors->first('flag') }}</li>
					@endif
					
				</ul>
			</div>
		</div>
    @endif
    <div class="col-md-12">
        <a href="" class="btn btn-xs btn-success pull-right" data-toggle="modal" data-target="#modaltambah">+ Tambah Data</a>
    </div>
	<div class="col-lg-12">
		<!-- Traffic sources -->
		<div class="panel panel-flat" style="min-height:350px !important;">
			<div class="panel-heading">
                <h3 class="panel-title">Daftar Unit</h3>   
                
            </div>
            <div class="container-fluid">
                <table class="table table-basic table-striped" id="table">
                    <thead>
                        <tr>
                            <th class="text-left">No</th>
                            <th class="text-left">Jenis</th>
                            <th>Keterangan</th>
                            <th>Status</th>
                            <th>#</th>
                        </tr>
                    </thead>
                @php
                    $no=1;
                @endphp
                <tbody>
                
                    @foreach ($jenis as $im)

                        <tr>
                                <td class="text-left"><b>{{$no}}</b></td>
                                <td class="">{{$im->jenis}}</td>
                                <td class="text-left">{{$im->keterangan}}</td>
                                <td>
                                    @if ($im->flag==1)
                                        <span class="label label-primary">Aktif</span>
                                    @else
                                        <span class="label label-danger">Tidak Aktif</span>    
                                    @endif
                                </td>
                                <td>
                                    <div style="width:100px">
                                        <a class="btn btn-xs btn-info btn-edit" data-toggle="modal" data-target="#modalubah" data-value="{{ $im->id }}">
                                                    <i class="icon-pencil"></i>
                                                </a>
                                        <a href="#" class="btn btn-xs btn-danger btn-delete" data-toggle="modal" data-target="#modalhapus" data-value="{{ $im->id }}">
                                        <i class="icon-trash"></i>
                                    </a>  
                                </div> 
                                </td>
                            </tr>
                           
                        
                        @php
                            $no++;
                        @endphp
                    @endforeach

                </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('modal')
	<div class="modal fade" id="modaltambah" tabindex="-1" role="dialog">
		<div class="modal-dialog ">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Tambah Data Jenis Bencana</h4>
				</div>
				<div class="modal-body">
					<form action="{{ route('master-jenis.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div class="row">
                            <div class="col-md-12">
                                 <div class="form-group">	
                                    <label>Jenis</label>
                                    <input type="text" name="jenis" class="form-control" placeholder="Jenis">  
                                </div>  
                                <div class="form-group">	
                                    <label>Keterangan</label>
                                    <input type="text" name="keterangan"  class="form-control" placeholder="Keterangan">  
                                </div>  
                                <div class="form-group">	
                                    <label>Status</label>
                                    <select name="flag"  palceholder="Status" class="selectbox" style="">
                                        <option>- Pilih -</option>
                                        <option value="0">Tidak Aktif</option>
                                        <option value="1">Aktif</option>
                                        
                                    </select>
                                </div> 
                            </div>
                           
                        </div>
						
						
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalubah" tabindex="-1" role="dialog">
		<div class="modal-dialog ">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Ubah Data SDM</h4>
				</div>
				<div class="modal-body">
					<form id="form-update" method="POST" enctype="multipart/form-data">
						@csrf
						@method('PUT')
						<div class="row">
                            <div class="col-md-12">
                               
                                <div class="form-group">	
                                    <label>Jenis</label>
                                    <input type="text" name="jenis" id="jenis" class="form-control" placeholder="Jenis">  
                                </div>  
                                <div class="form-group">	
                                    <label>Keterangan</label>
                                    <input type="text" name="keterangan" id="keterangan" class="form-control" placeholder="Keterangan">  
                                </div>  
                                <div class="form-group">	
                                    <label>Status</label>
                                    <select name="flag" id="flag" palceholder="Status" class="selectbox" style="">
                                        <option>- Pilih -</option>
                                        <option value="0">Tidak Aktif</option>
                                        <option value="1">Aktif</option>
                                        
                                    </select>
                                </div>  
                                
                            </div>
                        </div>  
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<input type="submit" class="btn btn-success" value="Simpan Perubahan">
				</div>
				</form>
			</div>
		</div>
	</div>

	<div class="modal fade" id="modalhapus" tabindex="-1" role="dialog">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Konfirmasi Hapus Data Jenis</h4>
				</div>
				<div class="modal-body">
					<h5>Apakah anda yakin akan menghapus data ini?</h5>
				</div>
				<div class="modal-footer">
					<button type="button" data-dismiss="modal" class="btn btn-default">Batal</button>
					<a class="btn btn-danger" onclick="event.preventDefault(); document.getElementById('form-delete').submit();" style="cursor:pointer;">Ya, Saya Yakin</a>
					<form id="form-delete" method="POST" style="display: none;">
						@csrf
						@method('DELETE')
					</form>
				</div>
			</div>
		</div>
	</div>
@endsection
@section('footscript')
    <script type="text/javascript" src="{{asset('assets/js/plugins/forms/selects/bootstrap_select.min.js')}}"></script>
    <script>
    $(document).ready(function(){
        $('#table').DataTable();
        $(".selectbox").selectpicker({
            
        });
    	// binding data to modal edit
        $('#table').on('click', '.btn-edit', function(){
            var id = $(this).data('value')
			var flag = $("select#flag").selectpicker();
			
            $.ajax({
                url: "{{ url('master-jenis') }}/"+id+"/edit",
                success: function(res) {
					$('#form-update').attr('action', "{{ url('master-jenis') }}/"+id)
					$('#jenis').val(res.jenis);
                    $('#keterangan').val(res.keterangan);
                    flag.selectpicker('val', res.flag);
                   
                }
            })
        })

		// delete action
        $('#table').on('click', '.btn-delete', function(){
            var id = $(this).data('value')
			$('#form-delete').attr('action', "{{ url('master-jenis') }}/"+id)			
        })
        
    });
    
    </script>
<style>
.selectbox {
    width: 100% !important;
}

</style>
@endsection

resources/views/pages/master/user-data.blade.php
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <input type="hidden" id="id_user" name="id_user" value="{{$user->id}}">	
                <label>NIP</label>
                <input type="text" name="nip" class="form-control" placeholder="NIP" value="{{($sdm) ? $sdm->nip : ''}}">
            </div>  
            <div class="form-group">	
                <label>Nama</label>
                <input type="text" name="nama_lengkap" class="form-control" placeholder="Nama Lengkap" value="{{($sdm) ? $sdm->nama_lengkap : $user->name}}">
            </div>  
            <div class="form-group">	
                <label>Email</label>
                <input type="text" name="email" class="form-control" placeholder="Email" value="{{($sdm) ? $sdm->email : $user->email}}">
            </div>  
            <div class="form-group">	
                <label>No HP</label>
                <input type="text" name="tempat_lahir" class="form-control" placeholder="HP" value="{{($sdm) ? $sdm->tempat_lahir : ''}}">
            </div>  
            
            <div class="form-group">	
                <label>Dasar Penugasan</label>
                <input type="text" name="status_pegawai" class="form-control" placeholder="Dasar Penugasan" value="{{($sdm) ? $sdm->status_pegawai : ''}}">
            </div>  
            <div class="form-group">	
                <label>Asal Instansi</label>
                <input type="text" name="kedudukan" class="form-control" placeholder="Asal Instansi" value="{{($sdm) ? $sdm->kedudukan : ''}}">
            </div>  
            
        </div>
       
    </div>